544137: NoClassDefFoundError: org/apache/http/client/fluent/Executor
Isolate USSSDK initialization so it doesn't shut down all of MPC
- force early initialization
- handle initialization errors
- adapt UI in case of errors

Bug: 544137
Task-Url: https://bugs.eclipse.org/bugs/show_bug.cgi?id=544137